language: node_js
node_js:
  - lts/*
install:
  - yarn install # npm ci
  - yarn add -D @vuepress/plugin-google-analytics
  - yarn add -D @vuepress/plugin-active-header-links
  - yarn add -D @vuepress/plugin-back-to-top
script:
  - yarn vuepress build docs # npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  fqdn: wiki.pixeltail.cn
  on:
    branch: master